Repository WeAreTeam3ForFinal/Final_Team3, pull requests merged in 2023-02, with the labels that each got.

#79 #50_개설키워드
  FinalProject/WebContent/WEB-INF/view/MmOpenForm.jsp
Labels: fixCode

#83 #46 오토매칭 1차
  FinalProject/WebContent/WEB-INF/view/MainPage.jsp
  FinalProject/src/com/kkini/controller/MemaController.java
  FinalProject/src/com/kkini/controller/User.java
  FinalProject/src/com/kkini/dto/UserDTO.java
  FinalProject/src/com/kkini/mybatis/IMemaDAO.java
  FinalProject/src/com/kkini/mybatis/IUserDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaDAO.xml
  FinalProject/src/com/kkini/mybatis/mapper/userDAO.xml
Labels: newCode, Document, fixCode

#88 #56_개설&지원
  FinalProject/WebContent/WEB-INF/view/MmOpenForm.jsp
  FinalProject/WebContent/WEB-INF/view/Mm_Apply.jsp
  FinalProject/src/com/kkini/controller/MemaApplyController.java
  FinalProject/src/com/kkini/mybatis/IMemaApplyDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaApplyDAO.xml
Labels: newCode, fixCode

#90 #56_mmOpen_etc
  FinalProject/WebContent/WEB-INF/view/MainPage.jsp
  FinalProject/WebContent/WEB-INF/view/MmOpenForm.jsp
Labels: newCode, fixCode

#91 #49 회원가입 지역 완료
  FinalProject/WebContent/WEB-INF/view/AddrListAjax.jsp
  FinalProject/WebContent/WEB-INF/view/IntregionSearchModal.jsp
  FinalProject/WebContent/WEB-INF/view/LoginForm.jsp
  FinalProject/WebContent/WEB-INF/view/RegionListAjax.jsp
  FinalProject/WebContent/WEB-INF/view/Register_form.jsp
  FinalProject/WebContent/WEB-INF/view/regionSearchModal.jsp
  FinalProject/src/com/kkini/controller/Region.java
  FinalProject/src/com/kkini/controller/User.java
  FinalProject/src/com/kkini/dto/RegionDTO.java
  FinalProject/src/com/kkini/dto/UserDTO.java
  FinalProject/src/com/kkini/mybatis/IRegionDAO.java
  FinalProject/src/com/kkini/mybatis/IUserDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/RegionDAO.xml
  FinalProject/src/com/kkini/mybatis/mapper/userDAO.xml
Labels: newCode, fixCode

#94 #58_성별 다르거나 모집인원수 충족 시, 지원불가처리
  FinalProject/WebContent/WEB-INF/view/Mm_Apply.jsp
  FinalProject/src/com/kkini/controller/MemaApplyController.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaApplyDAO.xml
Labels: newCode, fixCode
