Repository WeAreTeam3ForFinal/Final_Team3, pull requests merged in 2023-01, with the labels that each got.

#2 #3 풀리퀘스트 테스트용 커밋
  FinalProject/WebContent/main_jyj2.jsp
Labels: fixCode

#4 #4 search-engine 수정
  FinalProject/WebContent/main_jyj2.jsp
Labels: fixCode

#6 #5 동아리 리스트 Ajax 처리
  FinalProject/WebContent/ClubListAjax.jsp
  FinalProject/WebContent/main_jyj2.jsp
Labels: newCode, fixCode

#9 #6 동아리 리스트 코드 추가 및 마이바티스 xml 생성
  FinalProject/WebContent/ClubListAjax.jsp
  FinalProject/WebContent/WEB-INF/dispatcher-servlet.xml
  FinalProject/WebContent/WEB-INF/web.xml
Labels: newCode, Document

#15 #11 동아리 리스트 마이바티스 구성
  FinalProject/WebContent/ClubListAjax.jsp
  FinalProject/WebContent/WEB-INF/dispatcher-servlet.xml
  FinalProject/WebContent/main_jyj2.jsp
  FinalProject/src/com/kkini/controller/ClubController.java
  FinalProject/src/com/kkini/dto/ClubDTO.java
  FinalProject/src/com/kkini/mybatis/IClubDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/ClubDAO.xml
Labels: newCode, Document, fixCode

#17 #12 마이바티스 임시
  FinalProject/WebContent/ClubListAjax.jsp
  FinalProject/WebContent/main_jyj2.jsp
  FinalProject/src/com/kkini/mybatis/mapper/ClubDAO.xml
Labels: fixCode

#20 #7 회원가입 페이지 구성
  FinalProject/WebContent/Register_Alignment_form.jsp
  FinalProject/WebContent/Register_form.jsp
  FinalProject/WebContent/assets/css/register.css
  FinalProject/WebContent/assets/images/logo.jpeg
Labels: newCode

#22 #13 동아리리스트 마이바티스
  FinalProject/WebContent/ClubListAjax.jsp
  FinalProject/WebContent/main_jyj2.jsp
  FinalProject/src/com/kkini/controller/ClubController.java
  FinalProject/src/com/kkini/mybatis/IClubDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/ClubDAO.xml
Labels: newCode, fixCode

#29 #19_메뉴메이트 지원
  FinalProject/WebContent/MainPage.jsp
  FinalProject/WebContent/Mm_Apply.jsp
  FinalProject/WebContent/oneButtonPopup.html
  FinalProject/src/com/kkini/controller/MemaApplyController.java
  FinalProject/src/com/kkini/dto/MemaDTO.java
  FinalProject/src/com/kkini/mybatis/IMemaApplyDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaApplyDAO.xml
Labels: newCode

#36 #22_메메개설방 상단바, 좌측메뉴 파일 분리
  FinalProject/WebContent/MmOpenForm.jsp
  FinalProject/WebContent/assets/css/open.css
  FinalProject/WebContent/assets/css/open2.css
  FinalProject/WebContent/kakaomap.jsp
  FinalProject/WebContent/memaOpenForm2.jsp
  FinalProject/WebContent/titleAndSubMenu.jsp
Labels: fixCode

#38 #15 회원정보테이블 입력완료
  FinalProject/WebContent/Register_Alignment_form.jsp
  FinalProject/src/com/kkini/controller/User.java
  FinalProject/src/com/kkini/dto/UserDTO.java
  FinalProject/src/com/kkini/mybatis/IUserDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/userDAO.xml
Labels: newCode

#40 #25 mm openform.jsp
  FinalProject/WebContent/MmOpenForm.jsp
  FinalProject/src/com/kkini/dto/MemaOpenDTO.java
  FinalProject/src/com/kkini/mybatis/IMemaDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaOpenDAO.xml
Labels: newCode, fixCode

#44 #30_메인페이지 개설 버튼 임의 추가, 메메 개설 dto,dao 수정
  FinalProject/WebContent/MainPage.jsp
  FinalProject/WebContent/MmOpenForm.jsp
  FinalProject/src/com/kkini/controller/MemaController.java
  FinalProject/src/com/kkini/dto/MemaOpenDTO.java
  FinalProject/src/com/kkini/mybatis/IMemaDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaOpenDAO.xml
Labels: fixCode

#47 #32 login
  FinalProject/WebContent/LoginForm.jsp
  FinalProject/WebContent/MainPage.jsp
  FinalProject/WebContent/Register_form.jsp
  FinalProject/WebContent/assets/css/main.css
  FinalProject/src/com/kkini/controller/User.java
  FinalProject/src/com/kkini/mybatis/IUserDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/userDAO.xml
Labels: newCode

#51 #32 메뉴메이트 리스트 출력
  FinalProject/WebContent/MainPage.jsp
  FinalProject/WebContent/MemaListAjax.jsp
  FinalProject/src/com/kkini/controller/ClubController.java
  FinalProject/src/com/kkini/controller/MemaController.java
  FinalProject/src/com/kkini/dto/MemaDTO.java
  FinalProject/src/com/kkini/mybatis/IMemaDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaDAO.xml
Labels: newCode, Document, fixCode

#53 #33_메뉴메이트 개설 지원 수정 및 추가
  FinalProject/WebContent/MmOpenForm.jsp
  FinalProject/WebContent/Mm_Apply.jsp
  FinalProject/src/com/kkini/controller/MemaApplyController.java
  FinalProject/src/com/kkini/controller/MemaController.java
  FinalProject/src/com/kkini/mybatis/IMemaApplyDAO.java
  FinalProject/src/com/kkini/mybatis/IMemaDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaApplyDAO.xml
  FinalProject/src/com/kkini/mybatis/mapper/MemaOpenDAO.xml
  Servers/.settings/org.eclipse.wst.server.core.prefs
Labels: newCode, fixCode

#56 #34_메인페이지 개설하기 버튼 추가
  FinalProject/WebContent/MainPage.jsp
Labels: newCode

#59 #33 메뉴메이트 리스트 마무리
  FinalProject/WebContent/ClubListAjax.jsp
  FinalProject/WebContent/MainPage.jsp
  FinalProject/WebContent/MemaListAjax.jsp
  FinalProject/WebContent/assets/css/main.css
  FinalProject/src/com/kkini/dto/MemaDTO.java
  FinalProject/src/com/kkini/mybatis/IMemaDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaDAO.xml
Labels: newCode, Document, fixCode

#61 #35 회원가입 끝
  FinalProject/WebContent/IdOverlapAjax.jsp
  FinalProject/WebContent/MainPage.jsp
  FinalProject/WebContent/NicknameOverlapAjax.jsp
  FinalProject/WebContent/Register_form.jsp
  FinalProject/src/com/kkini/controller/User.java
  FinalProject/src/com/kkini/mybatis/IUserDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/userDAO.xml
Labels: newCode

#62 #37 메뉴메이트 상세정보 페이지
  FinalProject/WebContent/MainPage.jsp
  FinalProject/WebContent/MemaListAjax.jsp
  FinalProject/WebContent/Mm_Apply.jsp
  FinalProject/src/com/kkini/controller/MemaApplyController.java
  FinalProject/src/com/kkini/dto/MemaDTO.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaApplyDAO.xml
  FinalProject/src/com/kkini/mybatis/mapper/MemaDAO.xml
Labels: newCode, Document, fixCode

#64 #39_joinMeMa
  FinalProject/WebContent/MainPage.jsp
  FinalProject/WebContent/Register_form.jsp
  FinalProject/WebContent/mainPage.kkini
  FinalProject/src/com/kkini/controller/User.java
  FinalProject/src/com/kkini/dto/MemaDTO.java
  FinalProject/src/com/kkini/dto/UserDTO.java
  FinalProject/src/com/kkini/mybatis/IUserDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/userDAO.xml
Labels: newCode

#65 #39-MainPageMemaList
  FinalProject/WebContent/LoginForm.jsp
  FinalProject/WebContent/MainPage.jsp
  FinalProject/src/com/kkini/controller/User.java
  FinalProject/src/com/kkini/dto/MemaDTO.java
  FinalProject/src/com/kkini/dto/UserDTO.java
  FinalProject/src/com/kkini/mybatis/IUserDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/userDAO.xml
Labels: newCode

#66 #40_viewForder
  FinalProject/WebContent/WEB-INF/view/AddrListAjax.jsp
  FinalProject/WebContent/WEB-INF/view/ClubListAjax.jsp
  FinalProject/WebContent/WEB-INF/view/IdOverlapAjax.jsp
  FinalProject/WebContent/WEB-INF/view/LoginForm.jsp
  FinalProject/WebContent/WEB-INF/view/MainPage.jsp
  FinalProject/WebContent/WEB-INF/view/MemaListAjax.jsp
  FinalProject/WebContent/WEB-INF/view/MmOpenForm.jsp
  FinalProject/WebContent/WEB-INF/view/Mm_Apply.jsp
  FinalProject/WebContent/WEB-INF/view/NicknameOverlapAjax.jsp
  FinalProject/WebContent/WEB-INF/view/RegionCheckAjax.jsp
  FinalProject/WebContent/WEB-INF/view/RegionListAjax.jsp
  FinalProject/WebContent/WEB-INF/view/Register_Alignment_form.jsp
  FinalProject/WebContent/WEB-INF/view/Register_form.jsp
  FinalProject/WebContent/WEB-INF/view/kakaomap.jsp
  FinalProject/WebContent/WEB-INF/view/oneButtonPopup.html
  FinalProject/WebContent/WEB-INF/view/titleAndSubMenu.jsp
  FinalProject/WebContent/mainPage.kkini
  FinalProject/src/com/kkini/controller/ClubController.java
  FinalProject/src/com/kkini/controller/MemaApplyController.java
  FinalProject/src/com/kkini/controller/MemaController.java
  FinalProject/src/com/kkini/controller/Region.java
  FinalProject/src/com/kkini/controller/User.java
  Servers/Tomcat v8.5 Server at localhost-config/server.xml
Labels: fixCode

#72 #42 메메 검색기능
  FinalProject/WebContent/WEB-INF/dispatcher-servlet.xml
  FinalProject/WebContent/WEB-INF/view/MainPage.jsp
  FinalProject/WebContent/WEB-INF/view/MemaListAjax.jsp
  FinalProject/src/com/kkini/controller/MemaController.java
  FinalProject/src/com/kkini/controller/User.java
  FinalProject/src/com/kkini/dto/MemaDTO.java
  FinalProject/src/com/kkini/mybatis/IMemaDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaDAO.xml
Labels: newCode, Document, fixCode

#73 #43_메메개설폼 css 수정과 카카오맵 및 유효성 검사 기능 추가
  FinalProject/WebContent/WEB-INF/view/MmOpenForm.jsp
  FinalProject/WebContent/WEB-INF/view/kakaomap.jsp
  FinalProject/WebContent/assets/css/open2.css
Labels: newCode, fixCode

#76 #48_memaOpen
  FinalProject/WebContent/WEB-INF/view/MmOpenForm.jsp
  FinalProject/src/com/kkini/controller/MemaController.java
  FinalProject/src/com/kkini/dto/MemaOpenDTO.java
  FinalProject/src/com/kkini/mybatis/IMemaDAO.java
  FinalProject/src/com/kkini/mybatis/mapper/MemaOpenDAO.xml
Labels: newCode, fixCode

#77 #47_지원 수정
  FinalProject/WebContent/WEB-INF/view/Mm_Apply.jsp
  FinalProject/src/com/kkini/controller/MemaApplyController.java
  FinalProject/src/com/kkini/dto/MemaDTO.java
Labels: newCode, fixCode
